apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-tut
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kube-tut
  template:
    metadata:
      labels:
        app: kube-tut
    spec:
      containers:
      - name: kube-tut
        image: kinfe12/kube-tut:new
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
