apiVersion: v1
kind: Service
metadata:
  name: nginx-to-web
spec:
  selector:
    app: nginx-to-web
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-to-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-to-web
  template:
    metadata:
      labels:
        app: nginx-to-web
    spec:
      containers:
      - name: nginx-to-web
        image: kinfe12/kube-tut2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
